### ISSUE TITLE
Errors without stacks break clean-stack

### ISSUE THREAD

**Issue by SEAPUNK** [sindresorhus/clean-stack#1]
Strangely enough, such errors actually occur: https://github.com/kawanet/msgpack-lite/issues/51

Will this module handle such cases?

**Comment by sindresorhus** [comment]
Well, yes, because you pass the `stack` here, not the error. So you could do `cleanStack(error.stack || '')`.

**Comment by SEAPUNK** [comment]
Oh, right, I'm posting the issue in the wrong module, then -- I've had this issue in `aggregate-error`, so I thought this would be the source. :)
