### ISSUE TITLE
os.homedir() is not a function (not available in browser via webpack)

### ISSUE THREAD

**Issue by tnightingale** [sindresorhus/clean-stack#4]
I have clean-stack being added as a dependency of [p-any](https://www.npmjs.com/package/p-any). And [a recent change/feature](https://github.com/sindresorhus/clean-stack/commit/73edc1c4efa479078f73ce6465c3e4f5e3961ebc#diff-168726dbe96b3ce427e7fedce31bb0bcR6) breaks in browsers via webpack (possibly browserify too?).

I'm not familiar with Webpack's partial support of built-in nodejs APIs and/or why os.homedir is undefined (as opposed to being non-fatal, eg: a no-op). Apologies if this is known or deliberately not supported.

**Comment by kevva** [comment]
This is an issue with webpack and not this module. Since `os.homedir()` was added pretty recently they might just not gotten to it yet.

However, I've added i PR to them which fixes your issue https://github.com/webpack/node-libs-browser/pull/62.

**Comment by tnightingale** [comment]
Oh thanks. That makes sense, I was unsure about the history of that method.
