### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/clean-stack#6]
This module is used in `p-*` modules which should support being run in browsers. Would it be possible to make the dependency on `os` optional?

See https://github.com/sindresorhus/is-reachable/issues/18

**Comment by kevva** [comment]
Might be related to https://github.com/webpack/node-libs-browser/pull/62.

**Comment by floydpink** [comment]
@kevva - since https://github.com/jspm/nodelibs-os/pull/3 is now merged and released, how can `clean-stack` installation be changed use the new version of that library?

Is there a dependency update that needs to be done on this project somewhere?

**Comment by SamVerschueren** [comment]
Nope, you have to upgrade SystemJS if you use that. Not sure how webpack handles the os dependency.

**Comment by kevva** [comment]
@SamVerschueren, https://github.com/webpack/node-libs-browser/pull/62.

**Comment by silverwind** [comment]
Wouldn't it be better to have a check if the script runs in the browser and only attempt to load `os` when that fails? E.g. test for `window`.

**Comment by sindresorhus** [comment]
> Or alternatively, use a separate browser.js. I'd wager browser stack traces need more individual fixes anyways.

Probably, but I personally don't need browser compatibility. PR welcome to improve browser compatibility though.

**Comment by Jblew** [comment]
Hi guys! Please look at my PR: https://github.com/sindresorhus/clean-stack/pull/13 :)
